# Generated by Django 2.2.5 on 2021-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='作成日時'),
        ),
    ]
